### Get main page
GET http://localhost:5045

### Get all games
GET http://localhost:5045/games

### Get game by id
GET http://localhost:5045/games/7

### Post new game
POST http://localhost:5045/games
Content-Type: application/json

{
  "name": "FIFA 2025",
  "genre": "Sports",
  "price": 49.99,
  "releaseDate": "2025-10-01"
}