### Get main page
GET http://localhost:5045

### Get all games
GET http://localhost:5045/games

### Get game by id
GET http://localhost:5045/games/2

### Post new game
POST http://localhost:5045/games
Content-Type: application/json

{
  "Name": "Assassin's Creed Valhalla",
  "GenreId": 3,
  "Price": 39.99,
  "ReleaseDate": "2020-11-10"
}

### Update game by id
PUT http://localhost:5045/games/4
Content-Type: application/json

{
  "Name":  "Counter-Strike: Global Offensive",
  "GenreId": 2,
  "Price": 19.49,
  "ReleaseDate": "2012-08-21"
}

### Delete game by id
DELETE http://localhost:5045/games/8